// Configuration centralisée des prix d'abonnement
export const PRICING_PLANS = {
  starter: {
    id: "starter",
    name: "Starter",
    price: 20,
    originalPrice: 30,
    discount: "-33%",
    period: "/mois",
    description: "Pour démarrer et tester",
    priceId: "price_starter_monthly",
    features: [
      "1 établissement",
      "5 utilisateurs max",
      "Gestion stocks & gaspillage",
      "Alertes automatiques",
      "Checklist employés",
      "Rapports basiques",
    ],
    excludedFeatures: [
      "Prévisions & calculateur",
      "Multi-sites",
    ],
  },
  pro: {
    id: "pro",
    name: "Pro",
    price: 80,
    originalPrice: 100,
    discount: "-20%",
    period: "/mois",
    description: "Tout ce qu'il faut pour piloter vos marges",
    priceId: "price_pro_monthly",
    popular: true,
    features: [
      "Jusqu'à 3 établissements",
      "Utilisateurs illimités",
      "Toutes fonctionnalités Starter",
      "Prévisions intelligentes",
      "Calculateur de marges",
      "Gestion fournisseurs",
      "Rapports détaillés",
      "Support email prioritaire",
    ],
  },
  premium: {
    id: "premium",
    name: "Premium",
    price: 110,
    originalPrice: 150,
    discount: "-27%",
    period: "/mois",
    description: "Pour chaînes et groupes multi-sites",
    priceId: "price_premium_monthly",
    features: [
      "Établissements illimités",
      "Utilisateurs illimités",
      "Toutes les fonctionnalités Pro",
      "Vue consolidée multi-sites",
      "Intégrations API avancées",
      "Support prioritaire 24/7",
      "Account manager dédié",
      "Formation sur-mesure",
    ],
  },
} as const

export type PlanId = keyof typeof PRICING_PLANS
